//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.JobRunner.StockService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockService.IStockService")]
    public interface IStockService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetIncomePriceList", ReplyAction="http://tempuri.org/IStockService/GetIncomePriceListResponse")]
        ERP.StockService.DS_IncomePrice[] GetIncomePriceList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetIncomePriceList", ReplyAction="http://tempuri.org/IStockService/GetIncomePriceListResponse")]
        System.Threading.Tasks.Task<ERP.StockService.DS_IncomePrice[]> GetIncomePriceListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetOutcomeList", ReplyAction="http://tempuri.org/IStockService/GetOutcomeListResponse")]
        ERP.StockService.DS_Outcome[] GetOutcomeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetOutcomeList", ReplyAction="http://tempuri.org/IStockService/GetOutcomeListResponse")]
        System.Threading.Tasks.Task<ERP.StockService.DS_Outcome[]> GetOutcomeListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockServiceChannel : ERP.JobRunner.StockService.IStockService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockServiceClient : System.ServiceModel.ClientBase<ERP.JobRunner.StockService.IStockService>, ERP.JobRunner.StockService.IStockService {
        
        public StockServiceClient() {
        }
        
        public StockServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ERP.StockService.DS_IncomePrice[] GetIncomePriceList() {
            return base.Channel.GetIncomePriceList();
        }
        
        public System.Threading.Tasks.Task<ERP.StockService.DS_IncomePrice[]> GetIncomePriceListAsync() {
            return base.Channel.GetIncomePriceListAsync();
        }
        
        public ERP.StockService.DS_Outcome[] GetOutcomeList() {
            return base.Channel.GetOutcomeList();
        }
        
        public System.Threading.Tasks.Task<ERP.StockService.DS_Outcome[]> GetOutcomeListAsync() {
            return base.Channel.GetOutcomeListAsync();
        }
    }
}
