//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.JobRunner.ERP1.StockService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DS_IncomePrice", Namespace="http://schemas.datacontract.org/2004/07/ERP.StockService")]
    [System.SerializableAttribute()]
    public partial class DS_IncomePrice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BranchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContractField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ContractDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CurrencyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERP.JobRunner.ERP1.StockService.DS_IncomePriceItems[] DS_IncomePriceItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DS_StockIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DocDueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DsPaymentTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExternalDocDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalDocNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> IncomeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastPaymentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OperationalDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> OwnerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PJProjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PhysicalPersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RefIncomeTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal StatusIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BranchID {
            get {
                return this.BranchIDField;
            }
            set {
                if ((this.BranchIDField.Equals(value) != true)) {
                    this.BranchIDField = value;
                    this.RaisePropertyChanged("BranchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contract {
            get {
                return this.ContractField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractField, value) != true)) {
                    this.ContractField = value;
                    this.RaisePropertyChanged("Contract");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ContractDate {
            get {
                return this.ContractDateField;
            }
            set {
                if ((this.ContractDateField.Equals(value) != true)) {
                    this.ContractDateField = value;
                    this.RaisePropertyChanged("ContractDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CurrencyID {
            get {
                return this.CurrencyIDField;
            }
            set {
                if ((this.CurrencyIDField.Equals(value) != true)) {
                    this.CurrencyIDField = value;
                    this.RaisePropertyChanged("CurrencyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ERP.JobRunner.ERP1.StockService.DS_IncomePriceItems[] DS_IncomePriceItems {
            get {
                return this.DS_IncomePriceItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.DS_IncomePriceItemsField, value) != true)) {
                    this.DS_IncomePriceItemsField = value;
                    this.RaisePropertyChanged("DS_IncomePriceItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DS_StockID {
            get {
                return this.DS_StockIDField;
            }
            set {
                if ((this.DS_StockIDField.Equals(value) != true)) {
                    this.DS_StockIDField = value;
                    this.RaisePropertyChanged("DS_StockID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DocDueDate {
            get {
                return this.DocDueDateField;
            }
            set {
                if ((this.DocDueDateField.Equals(value) != true)) {
                    this.DocDueDateField = value;
                    this.RaisePropertyChanged("DocDueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DsPaymentTypeID {
            get {
                return this.DsPaymentTypeIDField;
            }
            set {
                if ((this.DsPaymentTypeIDField.Equals(value) != true)) {
                    this.DsPaymentTypeIDField = value;
                    this.RaisePropertyChanged("DsPaymentTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExternalDocDate {
            get {
                return this.ExternalDocDateField;
            }
            set {
                if ((this.ExternalDocDateField.Equals(value) != true)) {
                    this.ExternalDocDateField = value;
                    this.RaisePropertyChanged("ExternalDocDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalDocNumber {
            get {
                return this.ExternalDocNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalDocNumberField, value) != true)) {
                    this.ExternalDocNumberField = value;
                    this.RaisePropertyChanged("ExternalDocNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IncomeDate {
            get {
                return this.IncomeDateField;
            }
            set {
                if ((this.IncomeDateField.Equals(value) != true)) {
                    this.IncomeDateField = value;
                    this.RaisePropertyChanged("IncomeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastPaymentDate {
            get {
                return this.LastPaymentDateField;
            }
            set {
                if ((this.LastPaymentDateField.Equals(value) != true)) {
                    this.LastPaymentDateField = value;
                    this.RaisePropertyChanged("LastPaymentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OperationalDay {
            get {
                return this.OperationalDayField;
            }
            set {
                if ((this.OperationalDayField.Equals(value) != true)) {
                    this.OperationalDayField = value;
                    this.RaisePropertyChanged("OperationalDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> OwnerID {
            get {
                return this.OwnerIDField;
            }
            set {
                if ((this.OwnerIDField.Equals(value) != true)) {
                    this.OwnerIDField = value;
                    this.RaisePropertyChanged("OwnerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PJProjectID {
            get {
                return this.PJProjectIDField;
            }
            set {
                if ((this.PJProjectIDField.Equals(value) != true)) {
                    this.PJProjectIDField = value;
                    this.RaisePropertyChanged("PJProjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PhysicalPersonID {
            get {
                return this.PhysicalPersonIDField;
            }
            set {
                if ((this.PhysicalPersonIDField.Equals(value) != true)) {
                    this.PhysicalPersonIDField = value;
                    this.RaisePropertyChanged("PhysicalPersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> RefIncomeTypeID {
            get {
                return this.RefIncomeTypeIDField;
            }
            set {
                if ((this.RefIncomeTypeIDField.Equals(value) != true)) {
                    this.RefIncomeTypeIDField = value;
                    this.RaisePropertyChanged("RefIncomeTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DS_IncomePriceItems", Namespace="http://schemas.datacontract.org/2004/07/ERP.StockService")]
    [System.SerializableAttribute()]
    public partial class DS_IncomePriceItems : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BranchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ContractIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CurrencyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERP.JobRunner.ERP1.StockService.DS_IncomePrice DS_IncomePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DS_IncomePriceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERP.JobRunner.ERP1.StockService.DS_IncomePriseSimpleItemItems DS_IncomePriseSimpleItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DocDueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> HasWarrantyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OperationalDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> OwnerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ProductUnitIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> QualityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> StatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> VHFDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VHFNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> VatIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> VatPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarrantyDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WarrantyMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarrantyTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AddressID {
            get {
                return this.AddressIDField;
            }
            set {
                if ((this.AddressIDField.Equals(value) != true)) {
                    this.AddressIDField = value;
                    this.RaisePropertyChanged("AddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BranchID {
            get {
                return this.BranchIDField;
            }
            set {
                if ((this.BranchIDField.Equals(value) != true)) {
                    this.BranchIDField = value;
                    this.RaisePropertyChanged("BranchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ContractID {
            get {
                return this.ContractIDField;
            }
            set {
                if ((this.ContractIDField.Equals(value) != true)) {
                    this.ContractIDField = value;
                    this.RaisePropertyChanged("ContractID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CurrencyID {
            get {
                return this.CurrencyIDField;
            }
            set {
                if ((this.CurrencyIDField.Equals(value) != true)) {
                    this.CurrencyIDField = value;
                    this.RaisePropertyChanged("CurrencyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ERP.JobRunner.ERP1.StockService.DS_IncomePrice DS_IncomePrice {
            get {
                return this.DS_IncomePriceField;
            }
            set {
                if ((object.ReferenceEquals(this.DS_IncomePriceField, value) != true)) {
                    this.DS_IncomePriceField = value;
                    this.RaisePropertyChanged("DS_IncomePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DS_IncomePriceID {
            get {
                return this.DS_IncomePriceIDField;
            }
            set {
                if ((this.DS_IncomePriceIDField.Equals(value) != true)) {
                    this.DS_IncomePriceIDField = value;
                    this.RaisePropertyChanged("DS_IncomePriceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ERP.JobRunner.ERP1.StockService.DS_IncomePriseSimpleItemItems DS_IncomePriseSimpleItem {
            get {
                return this.DS_IncomePriseSimpleItemField;
            }
            set {
                if ((object.ReferenceEquals(this.DS_IncomePriseSimpleItemField, value) != true)) {
                    this.DS_IncomePriseSimpleItemField = value;
                    this.RaisePropertyChanged("DS_IncomePriseSimpleItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DocDueDate {
            get {
                return this.DocDueDateField;
            }
            set {
                if ((this.DocDueDateField.Equals(value) != true)) {
                    this.DocDueDateField = value;
                    this.RaisePropertyChanged("DocDueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> HasWarranty {
            get {
                return this.HasWarrantyField;
            }
            set {
                if ((this.HasWarrantyField.Equals(value) != true)) {
                    this.HasWarrantyField = value;
                    this.RaisePropertyChanged("HasWarranty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OperationalDay {
            get {
                return this.OperationalDayField;
            }
            set {
                if ((this.OperationalDayField.Equals(value) != true)) {
                    this.OperationalDayField = value;
                    this.RaisePropertyChanged("OperationalDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> OwnerID {
            get {
                return this.OwnerIDField;
            }
            set {
                if ((this.OwnerIDField.Equals(value) != true)) {
                    this.OwnerIDField = value;
                    this.RaisePropertyChanged("OwnerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ProductUnitID {
            get {
                return this.ProductUnitIDField;
            }
            set {
                if ((this.ProductUnitIDField.Equals(value) != true)) {
                    this.ProductUnitIDField = value;
                    this.RaisePropertyChanged("ProductUnitID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> QualityID {
            get {
                return this.QualityIDField;
            }
            set {
                if ((this.QualityIDField.Equals(value) != true)) {
                    this.QualityIDField = value;
                    this.RaisePropertyChanged("QualityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> VHFDate {
            get {
                return this.VHFDateField;
            }
            set {
                if ((this.VHFDateField.Equals(value) != true)) {
                    this.VHFDateField = value;
                    this.RaisePropertyChanged("VHFDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VHFNum {
            get {
                return this.VHFNumField;
            }
            set {
                if ((object.ReferenceEquals(this.VHFNumField, value) != true)) {
                    this.VHFNumField = value;
                    this.RaisePropertyChanged("VHFNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> VatID {
            get {
                return this.VatIDField;
            }
            set {
                if ((this.VatIDField.Equals(value) != true)) {
                    this.VatIDField = value;
                    this.RaisePropertyChanged("VatID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> VatPrice {
            get {
                return this.VatPriceField;
            }
            set {
                if ((this.VatPriceField.Equals(value) != true)) {
                    this.VatPriceField = value;
                    this.RaisePropertyChanged("VatPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarrantyDescription {
            get {
                return this.WarrantyDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.WarrantyDescriptionField, value) != true)) {
                    this.WarrantyDescriptionField = value;
                    this.RaisePropertyChanged("WarrantyDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> WarrantyMonth {
            get {
                return this.WarrantyMonthField;
            }
            set {
                if ((this.WarrantyMonthField.Equals(value) != true)) {
                    this.WarrantyMonthField = value;
                    this.RaisePropertyChanged("WarrantyMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarrantyType {
            get {
                return this.WarrantyTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.WarrantyTypeField, value) != true)) {
                    this.WarrantyTypeField = value;
                    this.RaisePropertyChanged("WarrantyType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DS_IncomePriseSimpleItemItems", Namespace="http://schemas.datacontract.org/2004/07/ERP.StockService")]
    [System.SerializableAttribute()]
    public partial class DS_IncomePriseSimpleItemItems : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERP.JobRunner.ERP1.StockService.DS_IncomePriceItems DS_IncomePriceItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ds_refBotanicTypeIDsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EnterDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> IdParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsFirstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MoistureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ERP.JobRunner.ERP1.StockService.DS_IncomePriceItems DS_IncomePriceItem {
            get {
                return this.DS_IncomePriceItemField;
            }
            set {
                if ((object.ReferenceEquals(this.DS_IncomePriceItemField, value) != true)) {
                    this.DS_IncomePriceItemField = value;
                    this.RaisePropertyChanged("DS_IncomePriceItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ds_refBotanicTypeIDs {
            get {
                return this.Ds_refBotanicTypeIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.Ds_refBotanicTypeIDsField, value) != true)) {
                    this.Ds_refBotanicTypeIDsField = value;
                    this.RaisePropertyChanged("Ds_refBotanicTypeIDs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EnterDate {
            get {
                return this.EnterDateField;
            }
            set {
                if ((this.EnterDateField.Equals(value) != true)) {
                    this.EnterDateField = value;
                    this.RaisePropertyChanged("EnterDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> IdParent {
            get {
                return this.IdParentField;
            }
            set {
                if ((this.IdParentField.Equals(value) != true)) {
                    this.IdParentField = value;
                    this.RaisePropertyChanged("IdParent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsFirst {
            get {
                return this.IsFirstField;
            }
            set {
                if ((this.IsFirstField.Equals(value) != true)) {
                    this.IsFirstField = value;
                    this.RaisePropertyChanged("IsFirst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Moisture {
            get {
                return this.MoistureField;
            }
            set {
                if ((this.MoistureField.Equals(value) != true)) {
                    this.MoistureField = value;
                    this.RaisePropertyChanged("Moisture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DS_Outcome", Namespace="http://schemas.datacontract.org/2004/07/ERP.StockService")]
    [System.SerializableAttribute()]
    public partial class DS_Outcome : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BranchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CurrencyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERP.JobRunner.ERP1.StockService.DS_OutcomeItems[] DS_OutcomeItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DS_StockIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DocDueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExternalDocDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalDocNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OperationalDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OutcomeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> OwnerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PJProjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PhysicalPersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RefAddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RefOutcomeTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal StatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> StructIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BranchID {
            get {
                return this.BranchIDField;
            }
            set {
                if ((this.BranchIDField.Equals(value) != true)) {
                    this.BranchIDField = value;
                    this.RaisePropertyChanged("BranchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CurrencyID {
            get {
                return this.CurrencyIDField;
            }
            set {
                if ((this.CurrencyIDField.Equals(value) != true)) {
                    this.CurrencyIDField = value;
                    this.RaisePropertyChanged("CurrencyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ERP.JobRunner.ERP1.StockService.DS_OutcomeItems[] DS_OutcomeItems {
            get {
                return this.DS_OutcomeItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.DS_OutcomeItemsField, value) != true)) {
                    this.DS_OutcomeItemsField = value;
                    this.RaisePropertyChanged("DS_OutcomeItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DS_StockID {
            get {
                return this.DS_StockIDField;
            }
            set {
                if ((this.DS_StockIDField.Equals(value) != true)) {
                    this.DS_StockIDField = value;
                    this.RaisePropertyChanged("DS_StockID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DocDueDate {
            get {
                return this.DocDueDateField;
            }
            set {
                if ((this.DocDueDateField.Equals(value) != true)) {
                    this.DocDueDateField = value;
                    this.RaisePropertyChanged("DocDueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExternalDocDate {
            get {
                return this.ExternalDocDateField;
            }
            set {
                if ((this.ExternalDocDateField.Equals(value) != true)) {
                    this.ExternalDocDateField = value;
                    this.RaisePropertyChanged("ExternalDocDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalDocNumber {
            get {
                return this.ExternalDocNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalDocNumberField, value) != true)) {
                    this.ExternalDocNumberField = value;
                    this.RaisePropertyChanged("ExternalDocNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OperationalDay {
            get {
                return this.OperationalDayField;
            }
            set {
                if ((this.OperationalDayField.Equals(value) != true)) {
                    this.OperationalDayField = value;
                    this.RaisePropertyChanged("OperationalDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OutcomeDate {
            get {
                return this.OutcomeDateField;
            }
            set {
                if ((this.OutcomeDateField.Equals(value) != true)) {
                    this.OutcomeDateField = value;
                    this.RaisePropertyChanged("OutcomeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> OwnerID {
            get {
                return this.OwnerIDField;
            }
            set {
                if ((this.OwnerIDField.Equals(value) != true)) {
                    this.OwnerIDField = value;
                    this.RaisePropertyChanged("OwnerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PJProjectID {
            get {
                return this.PJProjectIDField;
            }
            set {
                if ((this.PJProjectIDField.Equals(value) != true)) {
                    this.PJProjectIDField = value;
                    this.RaisePropertyChanged("PJProjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PhysicalPersonID {
            get {
                return this.PhysicalPersonIDField;
            }
            set {
                if ((this.PhysicalPersonIDField.Equals(value) != true)) {
                    this.PhysicalPersonIDField = value;
                    this.RaisePropertyChanged("PhysicalPersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> RefAddressID {
            get {
                return this.RefAddressIDField;
            }
            set {
                if ((this.RefAddressIDField.Equals(value) != true)) {
                    this.RefAddressIDField = value;
                    this.RaisePropertyChanged("RefAddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> RefOutcomeTypeID {
            get {
                return this.RefOutcomeTypeIDField;
            }
            set {
                if ((this.RefOutcomeTypeIDField.Equals(value) != true)) {
                    this.RefOutcomeTypeIDField = value;
                    this.RaisePropertyChanged("RefOutcomeTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> StructID {
            get {
                return this.StructIDField;
            }
            set {
                if ((this.StructIDField.Equals(value) != true)) {
                    this.StructIDField = value;
                    this.RaisePropertyChanged("StructID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DS_OutcomeItems", Namespace="http://schemas.datacontract.org/2004/07/ERP.StockService")]
    [System.SerializableAttribute()]
    public partial class DS_OutcomeItems : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BranchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ContractIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CurrencyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CurrentWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERP.JobRunner.ERP1.StockService.DS_Outcome DS_OutcomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DS_OutcomeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DocDueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OperationalDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> OwnerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ProductUnitIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> QualityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> StatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> VHFDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VHFNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BranchID {
            get {
                return this.BranchIDField;
            }
            set {
                if ((this.BranchIDField.Equals(value) != true)) {
                    this.BranchIDField = value;
                    this.RaisePropertyChanged("BranchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ContractID {
            get {
                return this.ContractIDField;
            }
            set {
                if ((this.ContractIDField.Equals(value) != true)) {
                    this.ContractIDField = value;
                    this.RaisePropertyChanged("ContractID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CurrencyID {
            get {
                return this.CurrencyIDField;
            }
            set {
                if ((this.CurrencyIDField.Equals(value) != true)) {
                    this.CurrencyIDField = value;
                    this.RaisePropertyChanged("CurrencyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CurrentWeight {
            get {
                return this.CurrentWeightField;
            }
            set {
                if ((this.CurrentWeightField.Equals(value) != true)) {
                    this.CurrentWeightField = value;
                    this.RaisePropertyChanged("CurrentWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ERP.JobRunner.ERP1.StockService.DS_Outcome DS_Outcome {
            get {
                return this.DS_OutcomeField;
            }
            set {
                if ((object.ReferenceEquals(this.DS_OutcomeField, value) != true)) {
                    this.DS_OutcomeField = value;
                    this.RaisePropertyChanged("DS_Outcome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DS_OutcomeID {
            get {
                return this.DS_OutcomeIDField;
            }
            set {
                if ((this.DS_OutcomeIDField.Equals(value) != true)) {
                    this.DS_OutcomeIDField = value;
                    this.RaisePropertyChanged("DS_OutcomeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DocDueDate {
            get {
                return this.DocDueDateField;
            }
            set {
                if ((this.DocDueDateField.Equals(value) != true)) {
                    this.DocDueDateField = value;
                    this.RaisePropertyChanged("DocDueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OperationalDay {
            get {
                return this.OperationalDayField;
            }
            set {
                if ((this.OperationalDayField.Equals(value) != true)) {
                    this.OperationalDayField = value;
                    this.RaisePropertyChanged("OperationalDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> OwnerID {
            get {
                return this.OwnerIDField;
            }
            set {
                if ((this.OwnerIDField.Equals(value) != true)) {
                    this.OwnerIDField = value;
                    this.RaisePropertyChanged("OwnerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ProductUnitID {
            get {
                return this.ProductUnitIDField;
            }
            set {
                if ((this.ProductUnitIDField.Equals(value) != true)) {
                    this.ProductUnitIDField = value;
                    this.RaisePropertyChanged("ProductUnitID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> QualityID {
            get {
                return this.QualityIDField;
            }
            set {
                if ((this.QualityIDField.Equals(value) != true)) {
                    this.QualityIDField = value;
                    this.RaisePropertyChanged("QualityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> VHFDate {
            get {
                return this.VHFDateField;
            }
            set {
                if ((this.VHFDateField.Equals(value) != true)) {
                    this.VHFDateField = value;
                    this.RaisePropertyChanged("VHFDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VHFNum {
            get {
                return this.VHFNumField;
            }
            set {
                if ((object.ReferenceEquals(this.VHFNumField, value) != true)) {
                    this.VHFNumField = value;
                    this.RaisePropertyChanged("VHFNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ERP1.StockService.IStockService")]
    public interface IStockService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetIncomePriceList", ReplyAction="http://tempuri.org/IStockService/GetIncomePriceListResponse")]
        ERP.JobRunner.ERP1.StockService.DS_IncomePrice[] GetIncomePriceList(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetIncomePriceList", ReplyAction="http://tempuri.org/IStockService/GetIncomePriceListResponse")]
        System.Threading.Tasks.Task<ERP.JobRunner.ERP1.StockService.DS_IncomePrice[]> GetIncomePriceListAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetOutcomeList", ReplyAction="http://tempuri.org/IStockService/GetOutcomeListResponse")]
        ERP.JobRunner.ERP1.StockService.DS_Outcome[] GetOutcomeList(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetOutcomeList", ReplyAction="http://tempuri.org/IStockService/GetOutcomeListResponse")]
        System.Threading.Tasks.Task<ERP.JobRunner.ERP1.StockService.DS_Outcome[]> GetOutcomeListAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockServiceChannel : ERP.JobRunner.ERP1.StockService.IStockService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockServiceClient : System.ServiceModel.ClientBase<ERP.JobRunner.ERP1.StockService.IStockService>, ERP.JobRunner.ERP1.StockService.IStockService {
        
        public StockServiceClient() {
        }
        
        public StockServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ERP.JobRunner.ERP1.StockService.DS_IncomePrice[] GetIncomePriceList(int Id) {
            return base.Channel.GetIncomePriceList(Id);
        }
        
        public System.Threading.Tasks.Task<ERP.JobRunner.ERP1.StockService.DS_IncomePrice[]> GetIncomePriceListAsync(int Id) {
            return base.Channel.GetIncomePriceListAsync(Id);
        }
        
        public ERP.JobRunner.ERP1.StockService.DS_Outcome[] GetOutcomeList(int Id) {
            return base.Channel.GetOutcomeList(Id);
        }
        
        public System.Threading.Tasks.Task<ERP.JobRunner.ERP1.StockService.DS_Outcome[]> GetOutcomeListAsync(int Id) {
            return base.Channel.GetOutcomeListAsync(Id);
        }
    }
}
