//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.OutcomeJobRunner.OutcomeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DS_Outcome", Namespace="http://schemas.datacontract.org/2004/07/ERP.OutcomeService.Models")]
    [System.SerializableAttribute()]
    public partial class DS_Outcome : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERP.OutcomeJobRunner.OutcomeService.DS_OutcomeItems[] DS_OutcomeItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExternalDocDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ERP.OutcomeJobRunner.OutcomeService.DS_OutcomeItems[] DS_OutcomeItems {
            get {
                return this.DS_OutcomeItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.DS_OutcomeItemsField, value) != true)) {
                    this.DS_OutcomeItemsField = value;
                    this.RaisePropertyChanged("DS_OutcomeItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExternalDocDate {
            get {
                return this.ExternalDocDateField;
            }
            set {
                if ((this.ExternalDocDateField.Equals(value) != true)) {
                    this.ExternalDocDateField = value;
                    this.RaisePropertyChanged("ExternalDocDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DS_OutcomeItems", Namespace="http://schemas.datacontract.org/2004/07/ERP.OutcomeService.Models")]
    [System.SerializableAttribute()]
    public partial class DS_OutcomeItems : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERP.OutcomeJobRunner.OutcomeService.DS_Outcome DS_OutcomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DS_OutcomeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OperationalDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ProductUnitIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ERP.OutcomeJobRunner.OutcomeService.DS_Outcome DS_Outcome {
            get {
                return this.DS_OutcomeField;
            }
            set {
                if ((object.ReferenceEquals(this.DS_OutcomeField, value) != true)) {
                    this.DS_OutcomeField = value;
                    this.RaisePropertyChanged("DS_Outcome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DS_OutcomeID {
            get {
                return this.DS_OutcomeIDField;
            }
            set {
                if ((this.DS_OutcomeIDField.Equals(value) != true)) {
                    this.DS_OutcomeIDField = value;
                    this.RaisePropertyChanged("DS_OutcomeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OperationalDay {
            get {
                return this.OperationalDayField;
            }
            set {
                if ((this.OperationalDayField.Equals(value) != true)) {
                    this.OperationalDayField = value;
                    this.RaisePropertyChanged("OperationalDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ProductUnitID {
            get {
                return this.ProductUnitIDField;
            }
            set {
                if ((this.ProductUnitIDField.Equals(value) != true)) {
                    this.ProductUnitIDField = value;
                    this.RaisePropertyChanged("ProductUnitID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OutcomeService.IOutcomeService")]
    public interface IOutcomeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOutcomeService/GetOutcomeList", ReplyAction="http://tempuri.org/IOutcomeService/GetOutcomeListResponse")]
        ERP.OutcomeJobRunner.OutcomeService.DS_Outcome[] GetOutcomeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOutcomeService/GetOutcomeList", ReplyAction="http://tempuri.org/IOutcomeService/GetOutcomeListResponse")]
        System.Threading.Tasks.Task<ERP.OutcomeJobRunner.OutcomeService.DS_Outcome[]> GetOutcomeListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOutcomeServiceChannel : ERP.OutcomeJobRunner.OutcomeService.IOutcomeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OutcomeServiceClient : System.ServiceModel.ClientBase<ERP.OutcomeJobRunner.OutcomeService.IOutcomeService>, ERP.OutcomeJobRunner.OutcomeService.IOutcomeService {
        
        public OutcomeServiceClient() {
        }
        
        public OutcomeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OutcomeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutcomeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutcomeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ERP.OutcomeJobRunner.OutcomeService.DS_Outcome[] GetOutcomeList() {
            return base.Channel.GetOutcomeList();
        }
        
        public System.Threading.Tasks.Task<ERP.OutcomeJobRunner.OutcomeService.DS_Outcome[]> GetOutcomeListAsync() {
            return base.Channel.GetOutcomeListAsync();
        }
    }
}
